/* =========================================================
   THE DAILY CIPHER — DEEP INTERACTIVE VISUALIZERS v2
   Self-contained teaching labs for every Learn cipher
========================================================= */
(() => {
  "use strict";
  const A="ABCDEFGHIJKLMNOPQRSTUVWXYZ", SP="ABCDEFGHIJKLMNÑOPQRSTUVWXYZ", PF="ABCDEFGHIKLMNOPQRSTUVWXYZ";
  const MORSE={A:".-",B:"-...",C:"-.-.",D:"-..",E:".",F:"..-.",G:"--.",H:"....",I:"..",J:".---",K:"-.-",L:".-..",M:"--",N:"-.",O:"---",P:".--.",Q:"--.-",R:".-.",S:"...",T:"-",U:"..-",V:"...-",W:".--",X:"-..-",Y:"-.--",Z:"--.."};
  const TRIG=[]; for(const a of ".-x")for(const b of ".-x")for(const c of ".-x"){const t=a+b+c;if(t!=="xxx")TRIG.push(t)}
  const BAC=Object.fromEntries(A.split("").map((ch,i)=>[ch,i.toString(2).padStart(5,"0").replace(/0/g,"A").replace(/1/g,"B")]));
  const CFG={
    caesar:{title:"Caesar Cipher",desc:"Shift the alphabet and inspect every letter mapping.",text:"THE DAILY CIPHER"},
    atbash:{title:"Atbash Cipher",desc:"Use the complete reversed alphabet and see why encryption and decryption are identical.",text:"THE DAILY CIPHER"},
    affine:{title:"Affine Cipher",desc:"Follow A=0 arithmetic through multiplication, addition, modular reduction, and inversion.",text:"AFFINE CIPHER"},
    railfence:{title:"Rail Fence Cipher",desc:"Watch plaintext move through the zigzag and then read the rails.",text:"SECRET MESSAGE"},
    playfair:{title:"Playfair Cipher",desc:"Build the 5×5 square, prepare digraphs, and apply the row/column/rectangle rules.",text:"HIDDEN CLUE"},
    hill:{title:"Hill Cipher",desc:"Convert letter blocks to vectors, multiply by a matrix, and reduce modulo 26.",text:"HIDDENCLUE"},
    aristocrat:{title:"Aristocrat Cipher",desc:"Inspect K1/K2/K3/random substitution rows and consistent word-pattern mappings.",text:"THE SECRET MESSAGE"},
    patristocrat:{title:"Patristocrat Cipher",desc:"See the same substitution process after original word boundaries disappear.",text:"PATTERN RECOGNITION"},
    baconian:{title:"Baconian Cipher",desc:"Keep the complete A/B table visible and step through one five-symbol group at a time.",text:"CRACK THE CODE"},
    xenocrypt:{title:"Spanish Xenocrypt",desc:"Visualize Spanish substitution with Ñ and keyed alphabet rows.",text:"LA SEÑAL SECRETA"},
    fractionatedmorse:{title:"Fractionated Morse",desc:"Follow plaintext → Morse → x separators → trigrams → keyed ciphertext.",text:"SECRET MESSAGE"},
    cryptarithm:{title:"Cryptarithm",desc:"Inspect column arithmetic, the hidden letter↔digit mapping, and extraction.",text:""},
    porta:{title:"Porta Cipher",desc:"Align the repeating key, choose one of 13 paired alphabets, and apply reciprocal substitution.",text:"SECRET MESSAGE"},
    nihilist:{title:"Nihilist Cipher",desc:"See Polybius coordinates for plaintext and key, then add or subtract each value.",text:"SECRET MESSAGE"},
    columnar:{title:"Complete Columnar Cipher",desc:"Fill the rectangle, label columns, and read complete columns in numeric key order.",text:"SECRET MESSAGE HIDES HERE"},
    checkerboard:{title:"Checkerboard Cipher",desc:"Build the keyed 5×5 board and highlight each row/column coordinate lookup.",text:"SECRET MESSAGE"},
    homophonic:{title:"Homophonic Cipher",desc:"See multiple number tokens assigned to common letters and decode each token unambiguously.",text:"SECRET MESSAGE"}
  };
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const mod=(n,m=26)=>((n%m)+m)%m;
  const letters=(s,alphabet=A)=>String(s||"").toUpperCase().split("").filter(c=>alphabet.includes(c)).join("");
  const clean=(s)=>String(s||"").toUpperCase().replace(/\s+/g," ").trim();
  const cleanSpanish=(s)=>String(s||"").toUpperCase().replace(/Ñ/g,"\u0000").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/\u0000/g,"Ñ").replace(/\s+/g," ").trim();
  const uniq=(key,alphabet=A)=>{let o="";for(const c of letters(key,alphabet)+alphabet)if(!o.includes(c))o+=c;return o};
  const rotateRight=(s,n)=>{n=mod(Number(n)||0,s.length);return n?s.slice(-n)+s.slice(0,-n):s};
  function inverse(a,m=26){for(let x=1;x<m;x++)if(mod(a*x,m)===1)return x;return null}
  function randShuffle(s){const a=s.split("");for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a.join("")}
  function keyedRows(kind,keyword,offset,alphabet=A){const k=uniq(keyword,alphabet),n=alphabet.length,o=mod(offset,n);if(kind==="K1")return [rotateRight(k,o),alphabet];if(kind==="K2")return [alphabet,rotateRight(k,o)];if(kind==="K3")return [k,rotateRight(k,o||1)];return [alphabet,randShuffle(alphabet)]}
  function sub(text,plain,cipher,alphabet=A){const source=alphabet===SP?cleanSpanish(text):clean(text);return source.split("").map(c=>alphabet.includes(c)?cipher[plain.indexOf(c)]:c).join("")}
  function alphaRows(p,c,spanish=false){return `<div class="alphabet-wrap"><div class="viz-info"><span>PLAIN ALPHABET</span></div><div class="alphabet-row${spanish?' spanish':''}">${p.split("").map(x=>`<div class="alphabet-cell">${esc(x)}</div>`).join("")}</div><div class="viz-info" style="margin-top:6px"><span>CIPHER ALPHABET</span></div><div class="alphabet-row${spanish?' spanish':''}">${c.split("").map(x=>`<div class="alphabet-cell accent">${esc(x)}</div>`).join("")}</div></div>`}
  function info(items){return `<div class="viz-grid">${items.map(([k,v])=>`<div class="viz-info"><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join("")}</div>`}
  function pipe(items){return `<div class="pipeline">${items.map(([k,v])=>`<div class="pipeline-stage"><span>${esc(k)}</span><div>${esc(v)}</div></div>`).join("")}</div>`}
  function card(title,body,cls=""){return `<section class="viz-card ${cls}"><h2>${esc(title)}</h2>${body}</section>`}
  function focus(items){return `<div class="stepper"><div class="stepper-status" data-step-status>Step through each transformation.</div><div class="stepper-controls"><button type="button" data-prev>Previous</button><button type="button" data-next>Next</button></div></div><div class="focus-grid">${items.map(x=>`<div class="viz-focus">${x}</div>`).join("")}</div>`}
  function table(head,rows,compact=false){return `<div class="viz-table-wrap"><table class="viz-table${compact?' compact':''}"><thead><tr>${head.map(x=>`<th>${esc(x)}</th>`).join("")}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${esc(x)}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`}
  function square(grid){return `<div class="square-grid">${grid.flat().map(c=>`<div class="square-cell">${esc(c)}</div>`).join("")}</div>`}
  function poly(squareObj,row=["1","2","3","4","5"],col=["1","2","3","4","5"]){let h=`<div class="poly-cell head"></div>`+col.map(x=>`<div class="poly-cell head">${esc(x)}</div>`).join("");for(let r=0;r<5;r++){h+=`<div class="poly-cell head">${esc(row[r])}</div>`+squareObj.grid[r].map(x=>`<div class="poly-cell">${esc(x)}</div>`).join("")}return `<div class="polybius">${h}</div>`}
  function buildPoly(keyword){const seq=uniq(letters(String(keyword).replace(/J/g,"I"),PF),PF),grid=[];const pos={};for(let r=0;r<5;r++){grid[r]=[];for(let c=0;c<5;c++){const ch=seq[r*5+c];grid[r][c]=ch;pos[ch]={r,c,val:(r+1)*10+c+1}}}pos.J=pos.I;return {seq,grid,pos}}
  function playSquare(keyword){const s=uniq(letters(String(keyword).replace(/J/g,"I"),PF),PF);const grid=[];const pos={};for(let r=0;r<5;r++){grid[r]=[];for(let c=0;c<5;c++){const ch=s[r*5+c];grid[r][c]=ch;pos[ch]={r,c}}}pos.J=pos.I;return {grid,pos}}
  function morseStream(text){const ws=clean(text).match(/[A-Z]+/g)||[];return ws.map(w=>w.split("").map(c=>MORSE[c]).join("x")).join("xx")}
  function portaChar(ch,key){const p=A.indexOf(ch),g=Math.floor(A.indexOf(key)/2);if(p<13)return A[13+mod(p+g,13)];return A[mod(p-13-g,13)]}
  function repeatKey(text,key){key=letters(key);let i=0,o="";for(const ch of clean(text)){if(A.includes(ch)){o+=key[i%key.length];i++}else o+=ch}return o}

  function baseControls(family){
    const c=CFG[family]; let f=[];
    if(family!=="cryptarithm")f.push(`<div class="viz-field full"><label for="viz-text">Plaintext</label><textarea id="viz-text" spellcheck="false">${esc(c.text)}</textarea></div>`);
    const add=(id,label,value,type="text",extra="")=>f.push(`<div class="viz-field"><label for="${id}">${label}</label><input id="${id}" type="${type}" value="${esc(value)}" ${extra}></div>`);
    const sel=(id,label,opts)=>f.push(`<div class="viz-field"><label for="${id}">${label}</label><select id="${id}">${opts.map(([v,l,s])=>`<option value="${esc(v)}"${s?' selected':''}>${esc(l)}</option>`).join("")}</select></div>`);
    if(family==="caesar")add("p1","Shift",3,"number",'min="0" max="25"');
    if(family==="affine"){add("p1","Multiplier a",5,"number");add("p2","Offset b",8,"number")}
    if(family==="railfence")add("p1","Rails",3,"number",'min="2" max="8"');
    if(family==="playfair")add("p1","Keyword","CIPHER");
    if(family==="hill"){add("p1","2×2 matrix","3,3,2,5");}
    if(["aristocrat","patristocrat"].includes(family)){sel("mode","Alphabet style",[["K1","K1",1],["K2","K2"],["K3","K3"],["RANDOM","Random"]]);add("p1","Keyword","CIPHER");add("p2","Offset",5,"number")}
    if(family==="baconian"){add("p1","A-class symbol","A");add("p2","B-class symbol","B")}
    if(family==="xenocrypt"){sel("mode","Alphabet style",[["K1","K1",1],["K2","K2"]]);add("p1","English keyword","SIGNAL");add("p2","Offset",5,"number")}
    if(family==="fractionatedmorse")add("p1","Keyword","CIPHER");
    if(family==="cryptarithm")sel("difficulty","Generator difficulty",[["Easy","Easy"],["Medium","Medium",1],["Hard","Hard"]]);
    if(family==="porta")add("p1","Keyword","CODE");
    if(family==="nihilist"){add("p1","Polybius keyword","CIPHER");add("p2","Additive keyword","SECRET")}
    if(family==="columnar")add("p1","Column key","4,2,3,1");
    if(family==="checkerboard"){add("p1","Polybius keyword","CIPHER");add("p2","Row headers","PLANT");add("p3","Column headers","NIGHT")}
    if(family==="homophonic")sel("difficulty","Mapping density",[["Easy","Easy"],["Medium","Medium",1],["Hard","Hard"]]);
    return `<div class="viz-control-grid">${f.join("")}</div><div class="viz-actions"><button id="viz-run" class="viz-button" type="button">Visualize</button><button id="viz-random" class="viz-secondary" type="button">Fresh example</button></div><div id="viz-status" class="viz-status" role="status" aria-live="polite"></div>`;
  }


  const LESSON={
    caesar:{input:"letters plus one fixed shift",key:"shift 0–25",output:"same-length shifted text",reverse:["Use the same shift value.","Move every ciphertext letter backward by the shift.","Wrap below A back through Z."],check:"All letters must use the same shift."},
    atbash:{input:"letters",key:"none — the reversed alphabet is fixed",output:"mirror-alphabet substitution",reverse:["Use the same A↔Z, B↔Y mapping.","Replace every ciphertext letter with its mirror partner."],check:"Applying Atbash twice must restore the input."},
    affine:{input:"letters converted with A=0…Z=25",key:"a and b",output:"E(x)=(ax+b) mod 26",reverse:["Find a⁻¹ mod 26.","For ciphertext value y, compute a⁻¹(y−b) mod 26.","Convert 0–25 back to letters."],check:"a must be coprime to 26."},
    railfence:{input:"continuous plaintext letters",key:"number of rails",output:"letters reordered by rail",reverse:["Draw the zigzag positions for the full message length.","Count positions on each rail and split ciphertext accordingly.","Fill the rails, then trace the zigzag path."],check:"Rail Fence changes order, not letter identity."},
    playfair:{input:"prepared letter pairs",key:"5×5 keyword square",output:"encrypted digraphs",reverse:["Use the same square.","Same row: move left. Same column: move up.","Rectangle: use the opposite corners just as in encryption."],check:"Prepare pairs before applying any square rule."},
    hill:{input:"numeric letter vectors",key:"invertible matrix mod 26",output:"matrix-mixed letter blocks",reverse:["Compute the key matrix inverse modulo 26.","Multiply each ciphertext vector by K⁻¹.","Reduce mod 26 and convert to letters."],check:"The determinant must be invertible mod 26."},
    aristocrat:{input:"plaintext with spaces",key:"one-to-one substitution alphabet",output:"substitution ciphertext with spaces preserved",reverse:["Build a ciphertext→plaintext mapping.","Use word shapes, repeats, frequency, and grammar together.","Propagate every proven mapping everywhere."],check:"One symbol must keep one plaintext meaning."},
    patristocrat:{input:"plaintext letters with spaces removed",key:"one-to-one substitution alphabet",output:"grouped spaceless ciphertext",reverse:["Ignore display groups as word boundaries.","Solve the monoalphabetic mapping from frequency/repeats/cribs.","Restore word spaces only after plaintext emerges."],check:"Displayed five-letter groups are not words."},
    baconian:{input:"letters",key:"two symbol classes representing A/B",output:"five symbols per plaintext letter",reverse:["Identify which visual class is A and which is B.","Split the stream into groups of five.","Normalize each group to A/B and look it up in the full table."],check:"Every plaintext letter consumes exactly five A/B positions."},
    xenocrypt:{input:"Spanish plaintext",key:"one-to-one Spanish substitution alphabet",output:"Spanish substitution ciphertext",reverse:["Use Spanish—not English—word/frequency clues.","Maintain a one-to-one mapping including Ñ when used.","Propagate mappings through repeated Spanish words/endings."],check:"The plaintext language is Spanish even if an English keyword built the key."},
    fractionatedmorse:{input:"plaintext letters",key:"keyword-derived alphabet",output:"letters representing Morse trigrams",reverse:["Map each ciphertext letter back to its trigram.","Concatenate all trigrams into one . - x stream.","Use x/xx separators to recover Morse letters/words, then decode Morse."],check:"Insert separators before splitting the stream into trigrams."},
    cryptarithm:{input:"letter-based decimal equations",key:"hidden one-to-one letter↔digit assignment",output:"a solved mapping and extraction",reverse:["Solve addition columns from right to left while tracking carries.","Enforce one-to-one digits and no leading zero.","Verify every equation numerically, then perform the extraction."],check:"A candidate mapping is not finished until every equation is true."},
    porta:{input:"plaintext plus repeating keyword",key:"keyword selects one of 13 paired rows",output:"reciprocal polyalphabetic ciphertext",reverse:["Repeat the same keyword alignment.","Use the exact same Porta row lookup on ciphertext.","Because Porta is reciprocal, that returns plaintext."],check:"A/B share one row, C/D share the next, and so on."},
    nihilist:{input:"plaintext Polybius values",key:"keyed square + repeating additive keyword",output:"sums of two Polybius coordinates",reverse:["Convert each additive-key letter to its Polybius value.","Subtract that value from the ciphertext number.","Look up the resulting valid row/column coordinate in the square."],check:"After subtraction, both coordinate digits should be 1–5."},
    columnar:{input:"plaintext written across a complete rectangle",key:"column-number permutation",output:"whole columns read in label order",reverse:["Compute equal column-chunk length.","Place ciphertext chunks under physical columns according to labels 1,2,3….","Read the restored rectangle across rows."],check:"Complete columnar means equal column lengths."},
    checkerboard:{input:"plaintext letters located in a keyed 5×5 board",key:"Polybius keyword + row/column headers",output:"row-header/column-header pairs",reverse:["Split ciphertext into pairs.","First token chooses the row; second chooses the column.","Read the plaintext letter at the intersection."],check:"Pair order is row first, column second."},
    homophonic:{input:"plaintext letters",key:"sets of ciphertext tokens assigned to letters",output:"token stream where common letters may vary",reverse:["Use a reverse token→letter map.","Replace each token with its unique plaintext letter.","For cryptanalysis, combine proven homophones when reasoning about frequency."],check:"Many tokens may mean E; one token may not mean both E and T."}
  };
  function lessonFor(f){const l=LESSON[f];if(!l)return "";return card("Start here — what this lab is doing",info([["INPUT",l.input],["KEY / RULE",l.key],["OUTPUT",l.output]])+`<div class="viz-lesson-note"><strong>Beginner check:</strong> ${esc(l.check)}</div>`,"viz-lesson");}
  function reverseFor(f){const l=LESSON[f];if(!l)return "";return card("How to reverse / solve it",`<ol class="viz-reverse-list">${l.reverse.map(x=>`<li>${esc(x)}</li>`).join("")}</ol><div class="viz-lesson-note">If any step above feels unclear, use the complete guide link at the top; the guide includes the full worked example and quick reference.</div>`,"viz-reverse");}

  function refFor(f){
    if(f==="baconian")return card("Complete Baconian reference",table(["Letter","A/B pattern"],Object.entries(BAC),true)+`<div class="deep-ref-note">The Daily Cipher uses the 26-letter A=0…Z=25 convention. Historical 24-letter conventions exist, so follow the table provided by a specific problem.</div>`,"viz-reference");
    if(f==="atbash")return card("Complete Atbash reference",alphaRows(A,A.split("").reverse().join("")),"viz-reference");
    if(f==="affine")return card("Affine reference",table(["Valid a","Inverse mod 26"],[[1,1],[3,9],[5,21],[7,15],[9,3],[11,19],[15,7],[17,23],[19,11],[21,5],[23,17],[25,25]],true)+`<div class="deep-ref-note">A=0, B=1, …, Z=25. Encrypt: E(x)=(ax+b) mod 26. Decrypt: D(y)=a⁻¹(y−b) mod 26.</div>`,"viz-reference");
    if(f==="fractionatedmorse")return card("Morse + trigram reference",`<details open><summary>Morse alphabet</summary>${table(["Letter","Morse"],Object.entries(MORSE),true)}</details><details><summary>26 trigram order</summary>${table(["#","Trigram"],TRIG.map((t,i)=>[i+1,t]),true)}</details>`,"viz-reference");
    if(f==="porta"){const rows=[];for(let g=0;g<13;g++){rows.push([A[g*2]+A[g*2+1],A.split("").map(ch=>portaChar(ch,A[g*2])).join("")])}return card("Porta tableau reference",table(["Key pair","Output under A–Z"],rows),"viz-reference")}
    if(["aristocrat","patristocrat"].includes(f))return card("Substitution solving reference",table(["Signal","Use"],[["1-letter words","Often A or I"],["Repeated letters","Preserved by monoalphabetic substitution"],["Common letters","E T A O I N are useful evidence, not proof"],["Common digraphs","TH HE IN ER AN RE"],["Consistency","One ciphertext letter must keep one plaintext meaning"]]),"viz-reference");
    if(f==="xenocrypt")return card("Spanish solving reference",table(["Signal","Examples"],[["Common letters","E A O S R N I L D T"],["2-letter words","DE LA EL EN UN ES"],["3-letter words","QUE LOS LAS DEL POR"],["Endings","-O -A -OS -AS -ES -CIÓN"]]),"viz-reference");
    if(f==="hill")return card("Hill reference",`<div class="deep-ref-note">A=0 … Z=25. Encrypt c=Kp mod 26. A matrix is usable only if its determinant is invertible mod 26.</div>`,"viz-reference");
    if(f==="checkerboard"||f==="nihilist")return card("Polybius convention",`<div class="deep-ref-note">This lab uses a keyed 5×5 square with I/J sharing a cell. Coordinates are row first, then column.</div>`,"viz-reference");
    if(f==="caesar")return card("Caesar rule",`<div class="deep-ref-note">Every letter moves the same number of alphabet positions. Encryption moves forward by the shift; decryption moves backward.</div>`,"viz-reference");
    if(f==="railfence")return card("Rail Fence rule",`<div class="deep-ref-note">Write letters in a repeating down/up zigzag. Encryption reads complete rails from top to bottom. Decryption marks the zigzag positions first, fills rails, then follows the zigzag.</div>`,"viz-reference");
    if(f==="playfair")return card("Playfair rules",table(["Pair geometry","Encrypt","Decrypt"],[["Same row","move right","move left"],["Same column","move down","move up"],["Rectangle","take opposite corners","same opposite-corner rule"]])+`<div class="deep-ref-note">This lab combines I/J in one cell and inserts X when a repeated-letter pair must be split or a final letter needs padding.</div>`,"viz-reference");
    if(f==="columnar")return card("Complete Columnar rule",`<div class="deep-ref-note">Write plaintext across rows. Pad to a full rectangle. Read the entire column labeled 1, then 2, then 3, and so on. For decryption, split ciphertext into equal column chunks and place them under those labels.</div>`,"viz-reference");
    if(f==="homophonic")return card("Homophonic rule",`<div class="deep-ref-note">One plaintext letter may own several ciphertext tokens, but every token decodes to exactly one plaintext letter. Equal plaintext letters therefore do not have to look equal in ciphertext.</div>`,"viz-reference");
    if(f==="cryptarithm")return card("Cryptarithm rules",table(["Constraint","Meaning"],[["One-to-one","each letter has one digit and each used digit has one letter"],["Leading letters","cannot be zero in a multi-digit number"],["Carries","connect adjacent arithmetic columns"],["Final check","every equation must be numerically true"]]),"viz-reference");
    return "";
  }

  function run(f){
    const status=$("viz-status"),out=$("viz-output");status.textContent="";status.className="viz-status";
    try{const text=f==="cryptarithm"?"":clean($("viz-text")?.value||"");if(f!=="cryptarithm"&&!text)throw Error("Enter plaintext first.");const r=RENDER[f](text);out.innerHTML=lessonFor(f)+refFor(f)+r+reverseFor(f);bindStepper(out);status.textContent="Visualization updated.";status.classList.add("viz-success")}catch(e){out.innerHTML=card("Could not visualize",`<p class="viz-error">${esc(e.message)}</p>`);status.textContent=e.message;status.classList.add("viz-error");console.error(e)}
  }

  const RENDER={
    caesar(text){const s=mod(Number($("p1").value),26),cipher=clean(text).split("").map(ch=>A.includes(ch)?A[mod(A.indexOf(ch)+s,26)]:ch).join("");const items=[...clean(text)].filter(ch=>A.includes(ch)).map(ch=>`${ch} (${A.indexOf(ch)}) + ${s} → ${A[mod(A.indexOf(ch)+s,26)]}`);return card("Shifted alphabets",alphaRows(A,A.slice(s)+A.slice(0,s)))+card("Transformation",pipe([["PLAINTEXT",text],["SHIFT",`+${s}`],["CIPHERTEXT",cipher]])+focus(items));},
    atbash(text){const rev=A.split("").reverse().join(""),cipher=sub(text,A,rev);const items=[...clean(text)].filter(ch=>A.includes(ch)).map(ch=>`${ch} ↔ ${rev[A.indexOf(ch)]}`);return card("Transformation",pipe([["PLAINTEXT",text],["REVERSED ALPHABET",rev],["CIPHERTEXT",cipher]])+focus(items));},
    affine(text){const a=mod(Number($("p1").value),26),b=mod(Number($("p2").value),26),inv=inverse(a);if(inv===null)throw Error("Multiplier a must be coprime with 26. Try 1,3,5,7,9,11,15,17,19,21,23,25.");let cipher="",items=[];for(const ch of clean(text)){if(!A.includes(ch)){cipher+=ch;continue}const x=A.indexOf(ch),y=mod(a*x+b,26);cipher+=A[y];items.push(`${ch}: (${a}×${x}+${b}) mod 26 = ${y} → ${A[y]}`)}return card("Key",info([["a",a],["b",b],["a⁻¹ mod 26",inv],["Decrypt formula",`${inv}(y−${b}) mod 26`]]))+card("Transformation",pipe([["PLAINTEXT",text],["CIPHERTEXT",cipher]])+focus(items));},
    railfence(text){const r=Math.max(2,Math.min(8,Number($("p1").value)||3)),t=letters(text);if(!t)throw Error("Enter letters to place on the rails.");const rows=Array.from({length:r},()=>Array(t.length).fill(""));let rail=0,dir=1;const order=[];for(let i=0;i<t.length;i++){rows[rail][i]=t[i];order.push(rail);if(rail===0)dir=1;else if(rail===r-1)dir=-1;rail+=dir}const cipher=rows.map(row=>row.join("")).join("");const grid=`<div class="rail-grid">${rows.map(row=>`<div class="rail-row">${row.map(ch=>`<div class="rail-cell${ch?' letter':''}">${esc(ch)}</div>`).join("")}</div>`).join("")}</div>`;return card("Zigzag grid",grid)+card("Read rails top to bottom",pipe([["CONTINUOUS PLAINTEXT",t],["RAIL PATH",order.join(" ")],["CIPHERTEXT",cipher]])+focus(t.split("").map((ch,i)=>`${ch} → rail ${order[i]+1}`)));},
    playfair(text){const kw=$("p1").value||"CIPHER",sq=playSquare(kw);let t=letters(text).replace(/J/g,"I"),pairs=[];for(let i=0;i<t.length;){let a=t[i],b=t[i+1];if(!b){b="X";i++}else if(a===b){b="X";i++}else i+=2;pairs.push(a+b)}let out="",items=[];for(const pair of pairs){const a=pair[0],b=pair[1],pa=sq.pos[a],pb=sq.pos[b];let x,y,rule;if(pa.r===pb.r){x=sq.grid[pa.r][(pa.c+1)%5];y=sq.grid[pb.r][(pb.c+1)%5];rule="same row → move right"}else if(pa.c===pb.c){x=sq.grid[(pa.r+1)%5][pa.c];y=sq.grid[(pb.r+1)%5][pb.c];rule="same column → move down"}else{x=sq.grid[pa.r][pb.c];y=sq.grid[pb.r][pa.c];rule="rectangle → other corners"}out+=x+y;items.push(`${pair} → ${x}${y} (${rule})`)}return card("Key square",info([["Keyword",kw.toUpperCase()],["Convention","I/J share one cell"]])+square(sq.grid))+card("Digraph preparation",pipe([["CLEAN TEXT",t],["PAIRS",pairs.join(" ")],["CIPHERTEXT",out]])+focus(items));},
    hill(text){const nums=String($("p1").value).split(/[,\s]+/).map(Number).filter(Number.isFinite);if(nums.length!==4)throw Error("Enter four matrix values such as 3,3,2,5.");const [a,b,c,d]=nums.map(x=>mod(x)),det=mod(a*d-b*c),di=inverse(det);if(di===null)throw Error("This matrix is not invertible modulo 26 because its determinant has no inverse.");let t=letters(text);if(t.length%2)t+="X";let out="",items=[];for(let i=0;i<t.length;i+=2){const x=A.indexOf(t[i]),y=A.indexOf(t[i+1]),u=mod(a*x+b*y),v=mod(c*x+d*y);out+=A[u]+A[v];items.push(`${t.slice(i,i+2)} [${x},${y}] → [${u},${v}] → ${A[u]}${A[v]}`)}const ia=mod(di*d),ib=mod(di*-b),ic=mod(di*-c),id=mod(di*a);return card("Matrix",info([["K",`[[${a},${b}],[${c},${d}]]`],["det K mod 26",det],["det⁻¹",di],["K⁻¹",`[[${ia},${ib}],[${ic},${id}]]`]]))+card("Block transformation",pipe([["PREPARED TEXT",t],["CIPHERTEXT",out]])+focus(items));},
    aristocrat(text){return renderSub(text,false,false)}, patristocrat(text){return renderSub(text,true,false)}, xenocrypt(text){return renderSub(text,false,true)},
    baconian(text){const sa=$("p1").value||"A",sb=$("p2").value||"B";if(sa===sb)throw Error("A-class and B-class symbols must be different.");let groups=[],items=[];for(const ch of clean(text)){if(ch===" "){groups.push("/");continue}if(!A.includes(ch))continue;const p=BAC[ch],g=p.split("").map(x=>x==="A"?sa:sb).join("");groups.push(g);items.push(`${g} → ${p} → ${ch}`)}return card("Generated groups",info([["A class",sa],["B class",sb]])+`<div class="viz-code big">${esc(groups.join(" "))}</div>`)+card("Decode group by group",focus(items));},
    fractionatedmorse(text){const kw=letters($("p1").value)||"CIPHER",alphabet=uniq(kw),raw=morseStream(text);let stream=raw;while(stream.length%3)stream+="x";const groups=stream.match(/.{3}/g)||[],out=groups.map(g=>alphabet[TRIG.indexOf(g)]).join("");const items=groups.map((g,i)=>`${g} → index ${TRIG.indexOf(g)+1} → ${alphabet[TRIG.indexOf(g)]}`);return card("Keyed alphabet",alphaRows(A,alphabet))+card("Fractionation pipeline",pipe([["PLAINTEXT",text],["MORSE + x SEPARATORS",raw],["PADDED STREAM",stream],["TRIGRAMS",groups.join(" ")],["CIPHERTEXT",out]])+focus(items));},
    cryptarithm(){if(typeof CipherEngine==="undefined")throw Error("Cipher engine did not load.");const difficulty=$("difficulty").value,r=CipherEngine.generate({type:"cryptarithm",difficulty});const map=r.parameters?.letterToDigit||{};const verify=String(r.ciphertext).split("\n").filter(line=>line.includes(" + ")&&line.includes(" = ")).map(line=>{const toNum=w=>Number([...w].map(ch=>map[ch]).join(""));const [lhs,rhs]=line.split(" = "),[a,b]=lhs.split(" + ");return `${line} → ${toNum(a)} + ${toNum(b)} = ${toNum(rhs)}`});return card("Generated arithmetic",`<div class="viz-code big">${esc(r.ciphertext)}</div>`)+card("Teaching view: hidden mapping",`<div class="mapping-grid">${Object.entries(map).sort().map(([l,d])=>`<div class="mapping-row"><strong>${esc(l)}</strong> → ${esc(d)}</div>`).join("")}</div><p>Practice hides this mapping. The visualizer reveals it so you can check deductions.</p>`)+card("Verify every equation",focus(verify));},
    porta(text){const key=letters($("p1").value)||"CODE",aligned=repeatKey(text,key);let out="",items=[],ki=0;for(const ch of clean(text)){if(!A.includes(ch)){out+=ch;continue}const k=key[ki%key.length],o=portaChar(ch,k);out+=o;items.push(`${ch} with key ${k} (${A[Math.floor(A.indexOf(k)/2)*2]}${A[Math.floor(A.indexOf(k)/2)*2+1]}) → ${o}`);ki++}return card("Key alignment",pipe([["PLAINTEXT",text],["REPEATING KEY",aligned],["CIPHERTEXT",out]])+focus(items));},
    nihilist(text){const sk=$("p1").value||"CIPHER",ak=letters($("p2").value)||"SECRET",sq=buildPoly(sk);let out=[],items=[],ki=0;for(const ch0 of clean(text)){if(ch0===" "){out.push("/");continue}let ch=ch0==="J"?"I":ch0;if(!PF.includes(ch))continue;const kc=(ak[ki%ak.length]==="J"?"I":ak[ki%ak.length]),pv=sq.pos[ch].val,kv=sq.pos[kc].val,n=pv+kv;out.push(n);items.push(`${ch}:${pv} + ${kc}:${kv} = ${n}`);ki++}return card("Keyed Polybius square",info([["Square keyword",sk.toUpperCase()],["Additive keyword",ak]])+poly(sq))+card("Additive pipeline",`<div class="viz-code big">${esc(out.join(" "))}</div>`+focus(items));},
    columnar(text){const key=String($("p1").value).split(/[,\s-]+/).map(Number).filter(Number.isFinite);if(key.length<2||new Set(key).size!==key.length||[...key].sort((a,b)=>a-b).some((v,i)=>v!==i+1))throw Error("Column key must be a permutation like 4,2,3,1.");let t=letters(text);while(t.length%key.length)t+="X";const rows=[];for(let i=0;i<t.length;i+=key.length)rows.push(t.slice(i,i+key.length).split(""));let out="",chunks=[];for(let label=1;label<=key.length;label++){const c=key.indexOf(label),chunk=rows.map(r=>r[c]).join("");chunks.push(chunk);out+=chunk}const grid=table(key.map(x=>String(x)),rows);return card("Complete rectangle",grid)+card("Column readout",pipe(chunks.map((v,i)=>[`COLUMN LABEL ${i+1}`,v]).concat([["CIPHERTEXT",out]]))+focus(chunks.map((v,i)=>`label ${i+1} → ${v}`)));},
    checkerboard(text){const pk=$("p1").value||"CIPHER",rh=letters($("p2").value).slice(0,5),ch=letters($("p3").value).slice(0,5);if(rh.length!==5||ch.length!==5||new Set(rh).size!==5||new Set(ch).size!==5)throw Error("Row and column headers must each contain five distinct letters.");const sq=buildPoly(pk);let out=[],items=[];for(const x0 of clean(text)){if(x0===" "){out.push("/");continue}const x=x0==="J"?"I":x0;if(!sq.pos[x])continue;const p=sq.pos[x],pair=rh[p.r]+ch[p.c];out.push(pair);items.push(`${x} at row ${p.r+1}, col ${p.c+1} → ${pair}`)}return card("Checkerboard",info([["Polybius keyword",pk.toUpperCase()],["Row headers",rh],["Column headers",ch]])+poly(sq,rh.split(""),ch.split("")))+card("Coordinate output",`<div class="viz-code big">${esc(out.join(" "))}</div>`+focus(items));},
    homophonic(text){if(typeof CipherEngine==="undefined")throw Error("Cipher engine did not load.");const difficulty=$("difficulty").value,r=CipherEngine.generate({type:"homophonic",difficulty,plaintext:text}),map=r.parameters?.mapping||{};const reverse={};for(const [l,ts] of Object.entries(map))for(const t of ts)reverse[t]=l;const tokens=r.ciphertext.split(/\s+/).filter(Boolean),items=tokens.filter(t=>t!=="/").map(t=>`${t} → ${reverse[t]||"?"}`);return card("Generated mapping",`<div class="mapping-grid">${Object.entries(map).map(([l,ts])=>`<div class="mapping-row"><strong>${esc(l)}</strong> → ${esc(ts.join(", "))}</div>`).join("")}</div>`)+card("Token stream",`<div class="viz-code big">${esc(r.ciphertext)}</div>`+focus(items));}
  };

  function renderSub(text,patri,spanish){const alphabet=spanish?SP:A,mode=$("mode").value,kw=$("p1").value||"CIPHER",off=Number($("p2").value)||1,[plain,cipher]=keyedRows(mode,kw,off,alphabet),ct=sub(text,plain,cipher,alphabet);let shown=ct;if(patri){const z=letters(ct,alphabet);shown=z.match(/.{1,5}/g)?.join(" ")||z}const items=[];for(const ch of clean(text)){if(!alphabet.includes(ch))continue;const o=cipher[plain.indexOf(ch)];items.push(`${ch} → ${o}`)}const freq={};for(const ch of letters(ct,alphabet))freq[ch]=(freq[ch]||0)+1;const freqRows=Object.entries(freq).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,12);const pattern=w=>{const m={},a=[],next={v:0};for(const ch of w){if(m[ch]===undefined)m[ch]=next.v++;a.push(m[ch])}return a.join("-")};const words=patri?[]:ct.split(/\s+/).filter(Boolean);const clues=card("Cryptanalysis clues from this example",table(["Cipher letter","Count"],freqRows,true)+(words.length?table(["Cipher word","Pattern"],words.slice(0,10).map(w=>[w,pattern(w)]),true):`<div class="deep-ref-note">Patristocrat display groups are not words. Focus on frequencies and repeated sequences in the continuous stream.</div>`));return card("Substitution rows",info([["Style",mode],["Keyword",kw.toUpperCase()],["Offset",off]])+alphaRows(plain,cipher,spanish))+card(patri?"Patristocrat output":"Substitution output",pipe([["PLAINTEXT",text],[patri?"REMOVE WORD SPACES":"WORD SPACES",""+(patri?letters(text,alphabet):"preserved")],["CIPHERTEXT",shown]])+focus(items))+clues;}

  function bindStepper(scope){const items=[...scope.querySelectorAll(".viz-focus")],prev=scope.querySelector("[data-prev]"),next=scope.querySelector("[data-next]"),status=scope.querySelector("[data-step-status]");if(!items.length||!prev||!next)return;let i=-1;const set=n=>{i=(n+items.length)%items.length;items.forEach((x,j)=>x.classList.toggle("is-highlighted",j===i));status.textContent=`Step ${i+1} of ${items.length}`};prev.onclick=()=>set(i-1);next.onclick=()=>set(i+1);set(0)}
  function fresh(f){const samples={caesar:"FOLLOW THE CLUE",atbash:"LOOK FOR PATTERNS",affine:"MODULAR ARITHMETIC",railfence:"TRANSPOSE THE LETTERS",playfair:"HIDDEN SIGNAL",hill:"MATRIX CODE",aristocrat:"EVERY PATTERN MATTERS",patristocrat:"FREQUENCY REVEALS STRUCTURE",baconian:"BREAK THE PATTERN",xenocrypt:"EL MENSAJE ESTA CERCA",fractionatedmorse:"MORSE SIGNAL",porta:"REPEATING KEY",nihilist:"NUMBER SIGNAL",columnar:"READ THE COLUMNS",checkerboard:"FIND THE SQUARE",homophonic:"LETTER FREQUENCY"};if($("viz-text")&&samples[f])$("viz-text").value=samples[f];if(f==="caesar")$("p1").value=Math.floor(Math.random()*25)+1;if(f==="affine"){const aa=[1,3,5,7,9,11,15,17,19,21,23,25];$("p1").value=aa[Math.floor(Math.random()*aa.length)];$("p2").value=Math.floor(Math.random()*26)}if(f==="railfence")$("p1").value=2+Math.floor(Math.random()*4);run(f)}
  function init(){const f=document.body.dataset.cipher,c=CFG[f];if(!c)return;try{if(localStorage.getItem("cipherTheme")==="light")document.body.classList.add("light-theme")}catch(_){/* Storage can be unavailable in embedded/privacy contexts. */}if(new URLSearchParams(location.search).get("embed")==="1"){document.body.classList.add("is-embedded");document.documentElement.classList.add("is-embedded")}$("viz-title").textContent=c.title;$("viz-description").textContent=c.desc;$("viz-controls").innerHTML=baseControls(f);$("viz-run").onclick=()=>run(f);$("viz-random").onclick=()=>fresh(f);run(f)}
  document.addEventListener("DOMContentLoaded",init,{once:true});
})();
